#!/usr/bin/env bash
# GENERATED by tools/workflow_compile.py from design/workflows/faq-abc-fixpoint-loop.toml -- do not hand-edit; recompile instead.
# design/FABLE-WORKFLOW-UNIT-COMPILER-SPEC.md's hydration-script artifact for workflow 'faq-abc-fixpoint-loop'.
#
# Idempotent-by-refusal (per the governing spec): re-running this script is safe. Per PHASE, if
# `led work open` refuses (duplicate-open, s22/s31 semantics), this script treats that phase as
# ALREADY HYDRATED -- its depends_on edges and obligation act (already issued the first time,
# by construction: they are only ever issued in the same run as a phase's own successful open)
# are skipped too, never re-issued. This is a per-phase idempotency granularity, not a
# per-statement one: `led work depends` itself has no duplicate-edge refusal in this kernel (it
# silently appends another advisory row), so this script's own skip-on-duplicate-open logic is
# what keeps a second full run from adding rows -- not a kernel property.
set -uo pipefail

LED="./legacy/led"
OBLIGATE_ASSIGNED_BY="reviewer"
OBLIGATE_OBLIGED_ACTOR="author"
NO_OBLIGATE=0
ASSUME_YES=0

usage() {
  echo "usage: $0 [--led <path>] [--obligate-assigned-by <principal>] [--obligate-obliged-actor <principal>] [--no-obligate] [--yes]" >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --led) LED="$2"; shift 2 ;;
    --obligate-assigned-by) OBLIGATE_ASSIGNED_BY="$2"; shift 2 ;;
    --obligate-obliged-actor) OBLIGATE_OBLIGED_ACTOR="$2"; shift 2 ;;
    --no-obligate) NO_OBLIGATE=1; shift ;;
    --yes) ASSUME_YES=1; shift ;;
    *) echo "$0: unrecognized argument '$1'" >&2; usage ;;
  esac
done

# deployment.json lives at the SCAFFOLD ROOT, read relative to the CURRENT WORKING DIRECTORY --
# not derived from --led's own path (both ./led and ./legacy/led resolve deployment.json this
# same way internally, from different directory depths, so deriving it from --led's dirname is
# fragile; this script is meant to be run from the scaffold root, exactly like `led` itself).
DEPLOYMENT="./deployment.json"

echo "-- workflow-unit hydration: faq-abc-fixpoint-loop (source design/workflows/faq-abc-fixpoint-loop.toml) --"
echo "-- led: $LED --"

# Returns 0 (already hydrated -- caller must skip this phase's edges/obligation) or 1 (freshly
# opened -- caller proceeds). Sets $OPEN_RC as the raw led exit code for callers that care.
open_phase() {
  local slug="$1" title="$2"
  out=$("$LED" work open "$slug" "$title" 2>&1)
  OPEN_RC=$?
  if [ "$OPEN_RC" -eq 0 ]; then
    echo "$out"
    return 1
  fi
  if printf '%s' "$out" | grep -qi "already has an opening act"; then
    echo "$slug: already hydrated (duplicate-open refusal, treated as done) -- skipping its depends_on edges and obligation act."
    return 0
  fi
  echo "$out" >&2
  echo "$0: REFUSED for an UNEXPECTED reason (not duplicate-open) -- stopping rather than guessing." >&2
  exit 1
}

open_phase "faq-abc-fixpoint-loop-author-draft" "author-draft phase of faq-abc-fixpoint-loop (from design/workflows/faq-abc-fixpoint-loop.toml)"
PHASE_AUTHOR_DRAFT_FRESH=$?

open_phase "faq-abc-fixpoint-loop-fresh-context-review" "fresh-context-review phase of faq-abc-fixpoint-loop (from design/workflows/faq-abc-fixpoint-loop.toml)"
PHASE_FRESH_CONTEXT_REVIEW_FRESH=$?

open_phase "faq-abc-fixpoint-loop-adjudicate" "adjudicate phase of faq-abc-fixpoint-loop (from design/workflows/faq-abc-fixpoint-loop.toml)"
PHASE_ADJUDICATE_FRESH=$?


if [ "$PHASE_FRESH_CONTEXT_REVIEW_FRESH" -eq 1 ]; then
  out=$("$LED" work depends "faq-abc-fixpoint-loop-fresh-context-review" "faq-abc-fixpoint-loop-author-draft" --type blocks-start 2>&1); rc=$?
  echo "$out"
  [ $rc -eq 0 ] || { echo "$0: REFUSED writing depends edge faq-abc-fixpoint-loop-fresh-context-review -> faq-abc-fixpoint-loop-author-draft" >&2; exit 1; }
else
  echo "faq-abc-fixpoint-loop-fresh-context-review: skipping depends_on edge to faq-abc-fixpoint-loop-author-draft (phase already hydrated)"
fi
if [ "$PHASE_ADJUDICATE_FRESH" -eq 1 ]; then
  out=$("$LED" work depends "faq-abc-fixpoint-loop-adjudicate" "faq-abc-fixpoint-loop-fresh-context-review" --type blocks-start 2>&1); rc=$?
  echo "$out"
  [ $rc -eq 0 ] || { echo "$0: REFUSED writing depends edge faq-abc-fixpoint-loop-adjudicate -> faq-abc-fixpoint-loop-fresh-context-review" >&2; exit 1; }
else
  echo "faq-abc-fixpoint-loop-adjudicate: skipping depends_on edge to faq-abc-fixpoint-loop-fresh-context-review (phase already hydrated)"
fi

if [ "$NO_OBLIGATE" -eq 1 ]; then
  echo "-- --no-obligate given: skipping the obligation act (fresh-context-review) --"
elif [ "1" = "1" ]; then
  echo "-- obligation act needed (row-1640 debt-surface guard): phase(s) fresh-context-review name an independent countersign --"
  echo "-- checking existing rows already written by '$OBLIGATE_OBLIGED_ACTOR' (these become retroactive debt-surface once obliged, per row-1640) --"
  HOST=$(python3 -c "import json; print(json.load(open('$DEPLOYMENT'))['host'])" 2>/dev/null)
  DB=$(python3 -c "import json; print(json.load(open('$DEPLOYMENT'))['db'])" 2>/dev/null)
  SCHEMA=$(python3 -c "import json; print(json.load(open('$DEPLOYMENT'))['schema'])" 2>/dev/null)
  if [ -n "$HOST" ] && [ -n "$DB" ] && [ -n "$SCHEMA" ]; then
    EXISTING_ROWS=$(psql -h "$HOST" -d "$DB" -tA -c \
      "SELECT count(*) FROM ${SCHEMA}.ledger WHERE actor = (SELECT id FROM ${SCHEMA}_kernel.principal WHERE name = '$OBLIGATE_OBLIGED_ACTOR');" 2>/dev/null || echo "?")
  else
    EXISTING_ROWS="?"
  fi
  echo "-- PROJECTED DEBT-SURFACE DELTA: obliging '$OBLIGATE_OBLIGED_ACTOR' will retroactively flag its $EXISTING_ROWS existing ledger row(s) as review debt (led work review-gap / led review-gap), per the row-1640 obligate-footgun teaching (retroactive, no temporal bound, self-amplifying). --"
  if [ "$ASSUME_YES" -eq 1 ]; then
    echo "-- --yes given: proceeding without interactive confirmation --"
    CONFIRMED=1
  else
    printf "Type OBLIGATE to confirm writing this obligation row, anything else to skip: "
    read -r REPLY
    if [ "$REPLY" = "OBLIGATE" ]; then CONFIRMED=1; else CONFIRMED=0; fi
  fi
  if [ "$CONFIRMED" -eq 1 ]; then
    out=$("$LED" obligate "faq-abc-fixpoint-loop-review" "$OBLIGATE_ASSIGNED_BY" "$OBLIGATE_OBLIGED_ACTOR" 2>&1)
    rc=$?
    if [ $rc -eq 0 ]; then
      echo "$out"
    elif printf '%s' "$out" | grep -qi "already carries an"; then
      echo "$OBLIGATE_OBLIGED_ACTOR: already obliged (treated as already hydrated) --"
      echo "$out"
    else
      echo "$out" >&2
      exit 1
    fi
  else
    echo "-- obligation act SKIPPED (not confirmed) -- re-run with --yes or type OBLIGATE to write it. --"
  fi
else
  echo "-- no phase in this workflow names an independent countersign (J2) -- no obligation act to hydrate. --"
fi

echo "-- hydration complete for faq-abc-fixpoint-loop --"
