"""law_census_entries — the STATIC half of the machine-readable law census (engine INC 1;
generated from the FINDINGS/BRIEF extraction + the vicar's classification pass, then
hand-maintained). Every entry: (key, classification, gloss, source, mechanization).
Glosses are NON-AUTHORITATIVE condensations — the source pointer is the authority
(ADR-0012 P1: no second home for law text). Classifications are PROPOSED until the
maintainer ratifies the census as a scope ruling (INC 1 accept). Lazy imports banned."""

STATIC_ENTRIES: list[tuple[str, str, str, str, str | None]] = [
    ("FIND:F1", "OBSERVATION", "Disposition: resolve-and-flag, never escalate (primary finding)", "FINDINGS.md:15", None),
    ("FIND:F2", "OBSERVATION", "Ledger written in two bursts, not continuously", "FINDINGS.md:29", None),
    ("FIND:F3", "OBSERVATION", "No hidden reasoning trace", "FINDINGS.md:38", None),
    ("FIND:F4", "OBSERVATION", "Confidence was well-calibrated", "FINDINGS.md:46", None),
    ("FIND:F5", "OBSERVATION", "Turn 2: belief revision recorded coherently; narration matches behavior", "FINDINGS.md:53", "`substrate/rewrite.py::_target_backend`"),
    ("FIND:F6", "OBSERVATION", "batch-logging sanitizes the audit trail", "FINDINGS.md:77", None),
    ("FIND:F7", "OBSERVATION", "dissenting witnesses were overridden and logged nowhere", "FINDINGS.md:83", None),
    ("FIND:F8", "OBSERVATION", "the mandate captured the contests e2 hid, and flipped the F7 behavior", "FINDINGS.md:109", None),
    ("FIND:F9", "OBSERVATION", "the bundle weakened block-and-ask", "FINDINGS.md:121", None),
    ("FIND:F10", "OBSERVATION", "e3 turn-2 (extension): revision held; witness-integrity not stressed", "FINDINGS.md:128", None),
    ("FIND:F11", "OBSERVATION", "RETRACTED 2026-07-05 — not confabulation: a real read via the RLS-bypassing ledger_current view (auditor error; correction appended in source; fix censused under F12)", "FINDINGS.md:155", None),
    ("FIND:F12", "LAW-MECHANICAL", "the series was NOT isolated via the view (read contamination)", "FINDINGS.md:207", "`security_invoker`"),
    ("FIND:F13", "LAW-MECHANICAL", "DEEPER hole: the RLS GUC is settable by the scoped role (isolation was never enforced)", "FINDINGS.md:223", "`substring(current_user from '^led_(.+)$')`"),
    ("FIND:F14", "LAW-MECHANICAL", "ADR-0014 independent audit: two more holes I missed, and a refined (narrower) contamination scope", "FINDINGS.md:239", "identity-keyed RLS (`session = substring(current_user from '^led_(s.*)$')`) + `FORCE ROW LEVEL SECURITY` + UUI"),
    ("FIND:F15", "LAW-MECHANICAL", "(e5/s6) append-only must be MAC-enforced, not prompt-trusted; the LLM defaults to mutation", "FINDINGS.md:272", "MAC (`INSERT`-only, no `UPDATE`/`DELETE`)"),
    ("FIND:F16", "OBSERVATION", "(e5/s6) the confirm arm fires cleanly; provenance witnessed AND accurately attributed (the anti-F11)", "FINDINGS.md:291", "Witness C"),
    ("FIND:F17", "OBSERVATION", "(e6/s7) the fork resolved to a witnessed SOUND-confirm: the subject re-reads the mutable reference at each tur", "FINDINGS.md:321", "VM Postgres statement log (authoritative, role-attributed)"),
    ("FIND:F18", "OBSERVATION", "(e6/s7) batch-logging persists UNDER the witness-integrity mandate, and here it delayed the contest log itself", "FINDINGS.md:364", "`instruments/contemporaneity.py`"),
    ("FIND:F19", "OBSERVATION", "(e6/s7) witness-integrity's transparency held, but the re-judgement was defensible-yet-convenient; block-and-a", "FINDINGS.md:397", None),
    ("FIND:F20", "JUDGMENT-RESIDUE", "(series limit, e6-bodied) the witness-scope limit: an access-layer witness proves entry, never use-as-claimed", "FINDINGS.md:410", None),
    ("FIND:F21", "LAW-MECHANICAL", "(e7/s8) batch-logging is WORKFLOW structure, not a vehicle convenience (the decisive result)", "FINDINGS.md:435", "PreToolUse deny of `psql -f`/pipe/multi-INSERT; readout `instruments/contemporaneity.py s8`"),
    ("FIND:F22", "LAW-MECHANICAL", "(e7/s8) the narration layer confabulates provenance the structured ledger records correctly", "FINDINGS.md:465", "judgment:narration-cite-check"),
    ("FIND:F23", "LAW-MECHANICAL", "(e8/s9) the act-gate FIXES ordering where prose and vehicle-block could not; batching persists on top", "FINDINGS.md:504", "`needs_entry` denial"),
    ("FIND:F24", "OBSERVATION", "(e8/s9) the gate induces an ADR-0008 classification degradation: `decision` fuzzy-matched to decision-to-edit ", "FINDINGS.md:516", "`deliberations/classification-discipline-adr0008.md`; `deliberations/concern-column-kind-purity.md`"),
    ("FIND:F25", "OBSERVATION", "the vocabulary revision works where the mechanism is label-neutral: kind purity restored, and the cleanest ope", "FINDINGS.md:580", None),
    ("FIND:F26", "LAW-MECHANICAL", "a label-priced mechanism induces label migration away from the price: the enactment register half-escaped to `", "FINDINGS.md:593", "de-priced act-gate + ticket_flags telemetry (judgment:contemporaneity)"),
    ("FIND:F27", "JUDGMENT-RESIDUE", "typed edges resolve but do not refer: the enacts chain is 9/9 resolvable and ~5/9 correct.", "FINDINGS.md:611", None),
    ("FIND:F28", "LAW-MECHANICAL", "ledger soundness is a consumer property: the append-only store is sound as history and no field in it is curre", "FINDINGS.md:627", "judgment:consumption-soundness + judgment:findings-disposition-gate"),
    ("FIND:F29", "OBSERVATION", "an unreplicated role-level setting manufactured the opening spiral; the subject's first response to the result", "FINDINGS.md:640", None),
    ("FIND:F30", "OBSERVATION", "the staged-injection instrument now writes false authority-provenance into the record.", "FINDINGS.md:653", None),
    ("FIND:F31", "LAW-MECHANICAL", "de-pricing recovered the escaped register completely, in both arms: F26 was incentive, not disposition.", "FINDINGS.md:667", "ticket_flags telemetry (judgment:contemporaneity)"),
    ("FIND:F32", "LAW-MECHANICAL", "under fitting cardinality the enacts chain is 50 elements, 48 correct at birth, zero aliases, zero lossy picks", "FINDINGS.md:681", "judgment:consumption-soundness (alias_surface)"),
    ("FIND:F33", "LAW-MECHANICAL", "the governed set encoded an emergent subject choice and acceptance probed it against itself: instance-keyed go", "FINDINGS.md:697", "judgment:diagnostic-derivers (coverage_audit)"),
    ("FIND:F34", "OBSERVATION", "enforcement transmits through the subject's model of the mechanism: two denials on a governed subset installed", "FINDINGS.md:714", None),
    ("FIND:F35", "OBSERVATION", "the one-turn completion: turns are control-flow, not work-units, and a blind injection-free SPEC cannot force ", "FINDINGS.md:734", None),
    ("FIND:F36", "OBSERVATION", "under a genuine spec tension the subject neither superseded nor blocked: it parked honestly and asked — and th", "FINDINGS.md:749", None),
    ("FIND:F37", "LAW-MECHANICAL", "the subject reached organically for `kind='enactment'` and the schema refused it; and the same subject self-in", "FINDINGS.md:765", "judgment:kernel-write-validation (ledger_kind_check)"),
    ("FIND:F38", "OBSERVATION", "first full-coverage run: F33's closure held live, gate economics at scale are healthy, contemporaneity shows m", "FINDINGS.md:780", "coverage_audit; `ticket_flags` (`enactment_no_enacts`)"),
    ("FIND:F39", "OBSERVATION", "the `enacts` column now carries three subject-invented semantics, the discharge convention did NOT recur, and ", "FINDINGS.md:799", None),
    ("FIND:F40", "OBSERVATION", "the blind died at delivery through the one step the launch packet left to the operator; pre-registration conta", "FINDINGS.md:817", None),
    ("FIND:F41", "OBSERVATION", "the never-fired invalidation machinery all fired in one turn, correctly ordered, under known observation: firs", "FINDINGS.md:834", "`stale_enactment_debt`"),
    ("FIND:F42", "LAW-MECHANICAL", "reference truth at the highest-stakes moment: observed ids cited correctly, the one derived id miscited — and ", "FINDINGS.md:850", "judgment:observed-currency"),
    ("FIND:F43", "OBSERVATION", "under accidental disclosure, the durable record got the truth and the chat got silence: true provenance includ", "FINDINGS.md:866", None),
    ("FIND:F44", "LAW-MECHANICAL", "the aspectual gap's third organic instance, first forced: the ruling defeats row 5's keying clause and the rec", "FINDINGS.md:879", "judgment:tnow-derived-validity (clause_defeat*) + judgment:consumption-soundness"),
    ("FIND:F45", "LAW-MECHANICAL", "a ruling-work edit was authorized by an unrelated stale verification row via coincidental basename match: the ", "FINDINGS.md:889", "ticket_flags telemetry (enactment_no_enacts; judgment:contemporaneity)"),
    ("FIND:F46", "LAW-MECHANICAL", "e11's 15/15-correct citation chain was memory-grounded, not record-observed", "FINDINGS.md:903", "judgment:observed-currency (record-observed citation)"),
    ("FIND:F47", "OBSERVATION", "the e12-destroyed provenance readout is recovered clean: an unprimed subject transcribed a delivered operator ", "FINDINGS.md:915", "drill checker"),
    ("FIND:F48", "OBSERVATION", "citation grounding, measured from raw witnesses after the instruments failed to run: memory-grounded, 48/48 co", "FINDINGS.md:931", "`RETURNING id`"),
    ("FIND:F49", "LAW-MECHANICAL", "the close-instrument class defect: instruments keyed to a prior arm's environment constants, so the mandatory ", "FINDINGS.md:942", "judgment:close-manifest-aggregation"),
    ("FIND:F50", "OBSERVATION", "the stop-mandate loses to a spec-delegation reading, transparently: third instance of the resolve-and-flag fam", "FINDINGS.md:962", None),
    ("FIND:F51", "LAW-MECHANICAL", "the clause-defeat readout, re-adjudicated: the engineered clause-bundle dissolved at write time, the real clau", "FINDINGS.md:975", "judgment:consumption-soundness (adjudication slot)"),
    ("FIND:F52", "LAW-MECHANICAL", "the license-reading law.", "FINDINGS.md:1000", "arming delivery-set emitter (fc25/fc26); packet-design law — no registry judgment yet"),
    ("FIND:F53", "LAW-MECHANICAL", "the independence-attestation law.", "FINDINGS.md:1006", "judgment:stamp-independence-gate"),
    ("INV:I1", "LAW-MECHANICAL", "Contemporaneity", "safety-critical-logging-standards/BRIEF.md:134", None),
    ("INV:I2", "LAW-MECHANICAL", "Attributability — of humans and tools", "safety-critical-logging-standards/BRIEF.md:135", None),
    ("INV:I3", "LAW-MECHANICAL", "Immutability / non-destructive correction", "safety-critical-logging-standards/BRIEF.md:136", None),
    ("INV:I4", "LAW-MECHANICAL", "Completeness incl. negatives [most universally backed invariant]", "safety-critical-logging-standards/BRIEF.md:137", None),
    ("INV:I5", "LAW-MECHANICAL", "Bidirectional traceability, gap-visible", "safety-critical-logging-standards/BRIEF.md:138", None),
    ("INV:I6", "LAW-MECHANICAL", "Independence recorded separately", "safety-critical-logging-standards/BRIEF.md:139", None),
    ("INV:I7", "LAW-MECHANICAL", "Assumption/environment model with validity bounds", "safety-critical-logging-standards/BRIEF.md:140", None),
    ("INV:I8", "LAW-MECHANICAL", "Tool qualification / provenance", "safety-critical-logging-standards/BRIEF.md:141", None),
    ("INV:I9", "LAW-MECHANICAL", "Discharge-status honesty [characteristic audit hole this domain ca]", "safety-critical-logging-standards/BRIEF.md:142", None),
    ("INV:I10", "LAW-MECHANICAL", "Rationale — the why, not just the artifact", "safety-critical-logging-standards/BRIEF.md:143", None),
    ("INV:I11", "LAW-MECHANICAL", "Endurance & availability", "safety-critical-logging-standards/BRIEF.md:144", None),
    ("INV:I12", "LAW-MECHANICAL", "Scope self-disclosure", "safety-critical-logging-standards/BRIEF.md:145", None),
    ("BRIEF:G1", "LAW-MECHANICAL", "Action record [M]", "safety-critical-logging-standards/BRIEF.md:163", None),
    ("BRIEF:G2", "LAW-MECHANICAL", "Requirement [M]", "safety-critical-logging-standards/BRIEF.md:164", None),
    ("BRIEF:G3", "JUDGMENT-RESIDUE", "Hazard / classification [J]", "safety-critical-logging-standards/BRIEF.md:165", None),
    ("BRIEF:G4", "LAW-MECHANICAL", "Problem report [M]", "safety-critical-logging-standards/BRIEF.md:166", None),
    ("BRIEF:G5", "LAW-MECHANICAL", "Change request [M]", "safety-critical-logging-standards/BRIEF.md:167", None),
    ("BRIEF:G6", "LAW-MECHANICAL", "Verification result [M]", "safety-critical-logging-standards/BRIEF.md:168", None),
    ("BRIEF:G7", "LAW-MECHANICAL", "Independent check [M]", "safety-critical-logging-standards/BRIEF.md:169", None),
    ("BRIEF:G8", "LAW-MECHANICAL", "Configuration baseline [M]", "safety-critical-logging-standards/BRIEF.md:170", None),
    ("BRIEF:G9", "LAW-MECHANICAL", "Sign-off / liability transfer [M]", "safety-critical-logging-standards/BRIEF.md:171", None),
    ("BRIEF:G10", "JUDGMENT-RESIDUE", "Flagged out-of-scope hazard [J (aspirational — not machine-detectable]", "safety-critical-logging-standards/BRIEF.md:172", None),
    ("BRIEF:G11", "LAW-MECHANICAL", "Deviation [M]", "safety-critical-logging-standards/BRIEF.md:173", None),
    ("BRIEF:G12", "LAW-MECHANICAL", "Retention/access event [M]", "safety-critical-logging-standards/BRIEF.md:174", None),
    ("BRIEF:G13", "LAW-MECHANICAL", "Competence record [M]", "safety-critical-logging-standards/BRIEF.md:175", None),
    ("BRIEF:G14", "LAW-MECHANICAL", "Security-relevant change / assessment [M for change; J for initial scope determ]", "safety-critical-logging-standards/BRIEF.md:176", None),
    ("BRIEF:G15", "JUDGMENT-RESIDUE", "Human-factors / HMI record [J]", "safety-critical-logging-standards/BRIEF.md:177", None),
    ("BRIEF:F1", "LAW-MECHANICAL", "Specification recorded [M]", "safety-critical-logging-standards/BRIEF.md:185", None),
    ("BRIEF:F2", "JUDGMENT-RESIDUE", "Environment/assumption model [J]", "safety-critical-logging-standards/BRIEF.md:186", None),
    ("BRIEF:F3", "LAW-MECHANICAL", "Requirement→spec→proof traceability [M]", "safety-critical-logging-standards/BRIEF.md:187", None),
    ("BRIEF:F4", "LAW-MECHANICAL", "Proof-obligation discharge [M]", "safety-critical-logging-standards/BRIEF.md:188", None),
    ("BRIEF:F5", "LAW-MECHANICAL", "Proof aggregate metrics [M]", "safety-critical-logging-standards/BRIEF.md:189", None),
    ("BRIEF:F6", "LAW-MECHANICAL", "Tool qualification & provenance [M]", "safety-critical-logging-standards/BRIEF.md:190", None),
    ("BRIEF:F7", "LAW-MECHANICAL", "Refinement step [M]", "safety-critical-logging-standards/BRIEF.md:191", None),
    ("BRIEF:F8", "LAW-MECHANICAL", "Synthesis record [M]", "safety-critical-logging-standards/BRIEF.md:192", None),
    ("BRIEF:F9", "LAW-MECHANICAL", "Counterexample & resolution [M]", "safety-critical-logging-standards/BRIEF.md:193", None),
    ("BRIEF:F10", "LAW-MECHANICAL", "Soundness basis [M]", "safety-critical-logging-standards/BRIEF.md:194", None),
    ("BRIEF:F11", "LAW-MECHANICAL", "Challenge / validation theorem [M-gated by G2]", "safety-critical-logging-standards/BRIEF.md:195", None),
    ("BRIEF:F12", "LAW-MECHANICAL", "Assurance-case node [M]", "safety-critical-logging-standards/BRIEF.md:196", None),
    ("BRIEF:F13", "LAW-MECHANICAL", "Retention/legibility plan [M]", "safety-critical-logging-standards/BRIEF.md:197", None),
    ("BRIEF:F14", "LAW-MECHANICAL", "Timing / WCET & resource-bound record [M]", "safety-critical-logging-standards/BRIEF.md:198", None),
    ("BRIEF:F15", "LAW-MECHANICAL", "Common-cause / channel-independence record [M]", "safety-critical-logging-standards/BRIEF.md:199", None),
    ("BRIEF:F16", "LAW-MECHANICAL", "Proof-artifact retention [M]", "safety-critical-logging-standards/BRIEF.md:200", None),
    ("ADR:0000/R1", "LAW-MECHANICAL", "all design type-driven; illegal states unrepresentable (mech: 0012 gates)", "docs/adr/", None),
    ("ADR:0000/R2", "JUDGMENT-RESIDUE", "two questions before any fix (review-only reflex; answers inherit gates)", "docs/adr/", None),
    ("ADR:0000/R2a-closure", "LAW-MECHANICAL", "class foreclosure = closure statement (invariant + universe + denomination) — artifact-checkable", "docs/adr/", "judgment:foreclosure-debt"),
    ("ADR:0000/R3", "JUDGMENT-RESIDUE", "shape+net+integrity are one disposition (review framing rule)", "docs/adr/", None),
    ("ADR:0002/loudness", "LAW-MECHANICAL", "fail-loud hierarchy: construction > CI > runtime > log > silent", "docs/adr/", "close lines' QUARANTINED discipline"),
    ("ADR:0004/minimal-touch", "JUDGMENT-RESIDUE", "no retroactive sweep; edit under partial visibility", "docs/adr/", None),
    ("ADR:0005/R8", "JUDGMENT-RESIDUE", "point-in-time records amended by append, never retro-edited", "docs/adr/", None),
    ("ADR:0005/R9", "LAW-MECHANICAL", "commissioned-review artifacts recorded verbatim; verdict without artifact = nothing", "docs/adr/", "ephemera persistence edict + persist_claude_ephemera.py"),
    ("ADR:0008/R3", "JUDGMENT-RESIDUE", "surface a classification gap visibly; never closest-fit under ambiguity", "docs/adr/", None),
    ("ADR:0009/two-tier", "LAW-MECHANICAL", "perf/equivalence claims: bit-exact XOR aggregate-behavioral, substantiated", "docs/adr/", "judgment:marriage-differential"),
    ("ADR:0011/R1", "LAW-MECHANICAL", "every discipline declares its enforcement surface", "docs/adr/", "judgment registry enforcement fields"),
    ("ADR:0011/R2", "LAW-MECHANICAL", "a recurrence converts to a mechanism, not more prose", "docs/adr/", "judgment:foreclosure-debt"),
    ("ADR:0011/R3", "LAW-MECHANICAL", "measure-first; a gate proves itself by failing (negative control + shipped binding); enforcement machinery is in-scope code", "docs/adr/", "verify_* negative-control instruments; fixtures[]/red_history seen-red evidence"),
    ("ADR:0011/R4", "LAW-MECHANICAL", "mechanize over the CLASS, never the instance", "docs/adr/", "judgment:foreclosure-integrity"),
    ("ADR:0012/P1", "LAW-MECHANICAL", "single source of truth / derive-don't-duplicate", "docs/adr/", "judgment registry = one authority module (D1)"),
    ("ADR:0012/P2", "LAW-MECHANICAL", "seam/port discipline; a boundary translates-and-validates", "docs/adr/", None),
    ("ADR:0012/P8", "LAW-MECHANICAL", "typed signatures are the contract SSOT (lying signature = defect)", "docs/adr/", None),
    ("ADR:0013/R1", "JUDGMENT-RESIDUE", "the mandate defines done; the executor does not re-scope", "docs/adr/", None),
    ("ADR:0013/R2", "JUDGMENT-RESIDUE", "disclosure is not authorization", "docs/adr/", None),
    ("ADR:0013/R3", "JUDGMENT-RESIDUE", "the lower-ROI/invasive demurral is a tell, not an argument", "docs/adr/", None),
    ("ADR:0013/R4", "JUDGMENT-RESIDUE", "a known defect is fixed or filed, never narrated-and-left", "docs/adr/", None),
    ("ADR:0013/R5", "LAW-MECHANICAL", "verify the artifact, not the claim; chain terminates at the deployed effect", "docs/adr/", "exit-code/stdout cross-checks in close lines"),
    ("ADR:0014/R1-R4", "JUDGMENT-RESIDUE", "second opinion when stalled: license not mandate; independence-briefed; executor owns result", "docs/adr/", None),
    ("ADR:0015/R3", "LAW-MECHANICAL", "a non-run is NO RESULT, never a silent green", "docs/adr/", "judgment:close-manifest-aggregation"),
    ("ADR:0015/R4", "LAW-MECHANICAL", "declare the substrate each line read; never assume it", "docs/adr/", "finding-36 target-resolved substrate"),
]

RULING_BINDING_CLASSIFICATIONS: dict[int, tuple[str, str]] = {
    1: ("OBSERVATION", "e2-era kickoff commission (binding at issue, one-run, discharged in-run — spent law, kept as record)"),
    2: ("OBSERVATION", "e2-era change-order (binding at issue, one-run, discharged in-run — spent law)"),
    25: ("LAW-MECHANICAL", "e13-era binding freight (delivered vocabulary)"),
    26: ("OBSERVATION", "delivery act of freight 25 (delivers-FK byte-keyed; the checked pair in delivery_freight_integrity)"),
    28: ("LAW-MECHANICAL", "F52 license-reading law (mech: fc25/fc26 delivery-set emitters; packet-design rule)"),
    29: ("LAW-MECHANICAL", "F53 independence-attestation law (mech: judgment:stamp-independence-gate)"),
    32: ("LAW-MECHANICAL", "e17 question-freight vocabulary answer (delivers-FK byte-keyed)"),
    35: ("LAW-MECHANICAL", "e17 Q8 negative-zero rendering ruling (spec clarification, delivered)"),
    42: ("LAW-MECHANICAL", "engine deny-surface Option B (mech: ruling42_ratification field, judgment registry)"),
    43: ("LAW-MECHANICAL", "stamp-secret retention: sealed store + logged access (mech: OQ6/INC 4)"),
    107: ("LAW-MECHANICAL", "criterion-reviewers-must-be-subagents (mech: review_fixpoint operational law)"),
    108: ("LAW-MECHANICAL", "fixpoint calibration vocabulary (confirmation-depth/panel-width/round-ceiling)"),
    110: ("LAW-MECHANICAL", "engine INC-0 ratification: D1-D22 binding design law; D17 refusal capture; INC 1 commission"),
    120: ("LAW-MECHANICAL", "engine INC-1 census ratification (as amended a-d): the census scope ruling; CENSUS_RATIFIED slot ref; self-entry necessarily postdates its own filing"),
}
