#!/usr/bin/env python3
"""GENERATED by tools/workflow_compile.py from design/workflows/faq-doc-then-fix-sequencing.toml -- do not hand-edit; recompile instead.
design/FABLE-WORKFLOW-UNIT-COMPILER-SPEC.md's driver artifact for workflow 'faq-doc-then-fix-sequencing'.

Executes the wave by kernel conversation: for each phase, in an order re-derived by re-polling
`led work claim` every round (never precomputed here -- the claim's own verdict is the gate,
per the governing spec's one design commitment), CLAIM (as --actor, default 'author'; a
refusal is a BLOCKED unit, reported and moved past, never overridden), DISPATCH (prints the
phase's prose brief -- authors/implements/reviews text from the source TOML -- for the caller's
own agent dispatch; this driver does not itself invoke an agent), CLOSE (--review-deferred by
default, or --review-bookkeeping --witness commit:<sha> when the phase's reviews clause names a
bookkeeping close -- see J4 in tools/workflow_compile.py's own docstring).

Usage:
    python3 faq-doc-then-fix-sequencing/drive.py --instance <token> [--led <path>] [--actor <phase>=<principal> ...]
                              [--commit-witness <phase>=<sha> ...] [--dry-run] [--rounds N]

--instance <token> is MANDATORY (spec Amendment, row 1660): it must be the SAME token given to
hydrate.sh for this wave -- slugs are `faq-doc-then-fix-sequencing-<instance>-<phase>`, so a different token drives a
DIFFERENT (or not-yet-hydrated) instance of this same TOML shape.

Exit 0 when the round budget completes (whether or not every phase closed -- BLOCKED units are
an ordinary, reportable outcome, not a driver failure); exit 1 on an unexpected kernel refusal
at CLOSE time (a close, unlike a claim, should not refuse once claimed, so that IS treated as
unexpected here) or a local usage error (exit 2).
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

STEM = "faq-doc-then-fix-sequencing"
TOML_REL = "design/workflows/faq-doc-then-fix-sequencing.toml"

PHASES = ['doc-authoring', 'ledger-citation', 'fix-authoring']
BRIEFS = {'doc-authoring': "authors: the orchestrator, who dispatches a document-only agent whose sole output is the docs describing what changed and why\nimplements: the document-only agent -- by construction, it produces documentation and nothing else in this phase\ndone: the docs describing what changed and why have landed (committed or otherwise durably recorded)\nlanding_zone: the repository's tracked source tree (the docs themselves, committed)", 'ledger-citation': "authors: the orchestrator -- and only the orchestrator, once it has itself read the produced docs\nimplements: the orchestrator, writing an ordinary ledger row (e.g. a decision row) citing the docs produced in doc-authoring\ndone: the orchestrator's own ledger row citing the produced docs lands, written only once the orchestrator has actually read them\nlanding_zone: the ledger -- an ordinary ledger row (this project's own worked instance used a decision row) citing the docs produced in doc-authoring", 'fix-authoring': "authors: the orchestrator, who dispatches a fix-only agent in a wholly separate dispatch -- one that, by construction, did not exist yet at the moment the ledger-citation row landed\nimplements: the fix-only agent\ndone: the fix-only agent's own ledger row(s) land, and by construction the agent's own dispatch postdates the ledger-citation row's id\nlanding_zone: the repository's tracked source tree (the fix itself, committed) plus the ledger row(s) the fix-only agent's own dispatch and close produce"}
BOOKKEEPING_PHASES = []
DEFAULT_ACTOR = "author"
INSTANCE_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def run_led(led: str, args: list[str], actor: str) -> tuple[int, str]:
    proc = subprocess.run([led] + args, capture_output=True, text=True,
                           env={**os.environ, "LED_ACTOR": actor})
    return proc.returncode, (proc.stdout + proc.stderr).strip()


def parse_kv(pairs: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for pair in pairs:
        if "=" not in pair:
            print(f"drive.py: '{pair}' is not <key>=<value>", file=sys.stderr)
            sys.exit(2)
        k, v = pair.split("=", 1)
        out[k] = v
    return out


def main(argv: list[str]) -> int:
    led = "./legacy/led"
    instance: str | None = None
    actor_overrides: dict[str, str] = {}
    commit_witness: dict[str, str] = {}
    dry_run = False
    rounds = len(PHASES) + 1

    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--led":
            led = argv[i + 1]; i += 2
        elif a == "--instance":
            instance = argv[i + 1]; i += 2
        elif a == "--actor":
            actor_overrides.update(parse_kv([argv[i + 1]])); i += 2
        elif a == "--commit-witness":
            commit_witness.update(parse_kv([argv[i + 1]])); i += 2
        elif a == "--dry-run":
            dry_run = True; i += 1
        elif a == "--rounds":
            rounds = int(argv[i + 1]); i += 2
        else:
            print(f"drive.py: unrecognized argument '{a}'", file=sys.stderr)
            return 2

    # --instance is MANDATORY and allowlist-validated BEFORE anything else runs (same
    # interpreter-boundary discipline as hydrate.sh's own check -- this token is concatenated
    # into every slug this run claims/closes).
    if not instance:
        print("drive.py: REFUSED -- --instance <token> is mandatory (spec Amendment, row 1660).",
              file=sys.stderr)
        return 2
    if not INSTANCE_TOKEN_RE.match(instance):
        print(f"drive.py: REFUSED -- --instance '{instance}' is not [A-Za-z0-9_-]+ "
              f"(interpreter-boundary discipline: this token is concatenated into every slug "
              f"this run claims/closes).", file=sys.stderr)
        return 2

    for phase in BOOKKEEPING_PHASES:
        if phase not in commit_witness:
            print(f"drive.py: REFUSED locally (not a kernel refusal) -- phase '{phase}' "
                  f"closes --review-bookkeeping and needs --commit-witness {phase}=<sha>, "
                  f"none given.", file=sys.stderr)
            return 2

    print(f"-- driving workflow '{STEM}' instance '{instance}' (source {TOML_REL}) via {led} --")

    closed: set[str] = set()
    for round_no in range(1, rounds + 1):
        made_progress = False
        for phase in PHASES:
            slug = f"{STEM}-{instance}-{phase}"
            if slug in closed:
                continue
            actor = actor_overrides.get(phase, DEFAULT_ACTOR)
            print(f"round {round_no}: attempting claim of '{slug}' as '{actor}' ...")
            if dry_run:
                print(f"  (dry-run) would run: LED_ACTOR={actor} {led} work claim {slug}")
                continue
            claim_rc, claim_out = run_led(led, ["work", "claim", slug], actor)
            if claim_rc != 0:
                print(f"  BLOCKED -- kernel refusal (verbatim):\n{claim_out}")
                continue
            print(f"  claimed: {claim_out}")
            brief = BRIEFS.get(phase, "")
            print(f"  DISPATCH -- brief for '{phase}':\n{brief}")
            if phase in BOOKKEEPING_PHASES:
                close_args = ["work", "close", slug, "shipped", "--review-bookkeeping",
                              "--witness", f"commit:{commit_witness[phase]}"]
            else:
                close_args = ["work", "close", slug, "shipped", "--review-deferred",
                              "--witness", f"unit:{slug}"]
            close_rc, close_out = run_led(led, close_args, actor)
            if close_rc != 0:
                print(f"  CLOSE REFUSED -- kernel refusal (verbatim):\n{close_out}",
                      file=sys.stderr)
                return 1
            print(f"  closed: {close_out}")
            closed.add(slug)
            made_progress = True
        if len(closed) == len(PHASES) or (not made_progress and not dry_run):
            break

    print(f"-- drive complete: {len(closed)}/{len(PHASES)} phase(s) closed --")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
