#!/usr/bin/env bash
# GENERATED by tools/workflow_compile.py from design/workflows/faq-doc-then-fix-sequencing.toml -- do not hand-edit; recompile instead.
# design/FABLE-WORKFLOW-UNIT-COMPILER-SPEC.md's hydration-script artifact for workflow 'faq-doc-then-fix-sequencing'.
#
# INSTANCE-QUALIFIED SLUGS (spec Amendment, 2026-07-18, ledger row 1660): a TOML is a reusable
# SHAPE, not a one-shot -- slugs burn permanently on open (s31), so without an instance token
# this workflow could be hydrated exactly ONCE per world. Every phase slug is therefore
# `faq-doc-then-fix-sequencing-<instance>-<phase>`, `--instance <token>` is MANDATORY, and idempotent-by-refusal
# semantics apply PER INSTANCE (two different --instance values are two independently
# claimable waves of the same TOML).
#
# Idempotent-by-refusal (per the governing spec): re-running this script FOR THE SAME INSTANCE
# is safe. Per PHASE, if `led work open` refuses (duplicate-open, s22/s31 semantics), this
# script treats that phase as ALREADY HYDRATED -- its depends_on edges and obligation act
# (already issued the first time, by construction: they are only ever issued in the same run as
# a phase's own successful open) are skipped too, never re-issued. This is a per-phase
# idempotency granularity, not a per-statement one: `led work depends` itself has no
# duplicate-edge refusal in this kernel (it silently appends another advisory row), so this
# script's own skip-on-duplicate-open logic is what keeps a second same-instance run from adding
# rows -- not a kernel property.
set -uo pipefail

# legacy-led-retirement pass (row 1149): flipped to served "./led" -- SAFE (unlike DRIVE_TEMPLATE
# below, still on legacy): every verb here (work open/depends, obligate) is COVERED, and every
# string matched in `$out` is the KERNEL's own RAISE EXCEPTION text either way.
LED="./led"
INSTANCE=""
OBLIGATE_ASSIGNED_BY="reviewer"
OBLIGATE_OBLIGED_ACTOR="author"
NO_OBLIGATE=0
ASSUME_YES=0

usage() {
  echo "usage: $0 --instance <token> [--led <path>] [--obligate-assigned-by <principal>] [--obligate-obliged-actor <principal>] [--no-obligate] [--yes]" >&2
  echo "  --instance <token>  MANDATORY. [A-Za-z0-9_-]+ -- one engagement of this TOML's shape;" >&2
  echo "                      slugs are faq-doc-then-fix-sequencing-<instance>-<phase>. Two different tokens are two" >&2
  echo "                      independently claimable waves of the same workflow." >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --instance) INSTANCE="$2"; shift 2 ;;
    --led) LED="$2"; shift 2 ;;
    --obligate-assigned-by) OBLIGATE_ASSIGNED_BY="$2"; shift 2 ;;
    --obligate-obliged-actor) OBLIGATE_OBLIGED_ACTOR="$2"; shift 2 ;;
    --no-obligate) NO_OBLIGATE=1; shift ;;
    --yes) ASSUME_YES=1; shift ;;
    *) echo "$0: unrecognized argument '$1'" >&2; usage ;;
  esac
done

# --instance is MANDATORY and allowlist-validated BEFORE anything else runs (interpreter-
# boundary discipline: a token that will be concatenated into every slug this run writes is
# refused loudly on shape, never silently sanitized or passed through).
if [ -z "$INSTANCE" ]; then
  echo "$0: REFUSED -- --instance <token> is mandatory (spec Amendment, row 1660)." >&2
  usage
fi
case "$INSTANCE" in
  *[!A-Za-z0-9_-]*|"")
    echo "$0: REFUSED -- --instance '$INSTANCE' is not [A-Za-z0-9_-]+ (interpreter-boundary discipline: this token is concatenated into every slug this run writes)." >&2
    exit 2
    ;;
esac

# deployment.json lives at the SCAFFOLD ROOT, read relative to the CURRENT WORKING DIRECTORY --
# not derived from --led's own path (both ./led and ./legacy/led resolve deployment.json this
# same way internally, from different directory depths, so deriving it from --led's dirname is
# fragile; this script is meant to be run from the scaffold root, exactly like `led` itself).
DEPLOYMENT="./deployment.json"

echo "-- workflow-unit hydration: faq-doc-then-fix-sequencing instance '$INSTANCE' (source design/workflows/faq-doc-then-fix-sequencing.toml) --"
echo "-- led: $LED --"

# Returns 0 (already hydrated -- caller must skip this phase's edges/obligation) or 1 (freshly
# opened -- caller proceeds). Sets $OPEN_RC as the raw led exit code for callers that care.
open_phase() {
  local slug="$1" title="$2"
  out=$("$LED" work open "$slug" "$title" 2>&1)
  OPEN_RC=$?
  if [ "$OPEN_RC" -eq 0 ]; then
    echo "$out"
    return 1
  fi
  if printf '%s' "$out" | grep -qi "already has an opening act"; then
    echo "$slug: already hydrated (duplicate-open refusal, treated as done) -- skipping its depends_on edges and obligation act."
    return 0
  fi
  echo "$out" >&2
  echo "$0: REFUSED for an UNEXPECTED reason (not duplicate-open) -- stopping rather than guessing." >&2
  exit 1
}

# Instance-qualified slugs, computed now that --instance has passed validation.
SLUG_DOC_AUTHORING="faq-doc-then-fix-sequencing-${INSTANCE}-doc-authoring"
SLUG_LEDGER_CITATION="faq-doc-then-fix-sequencing-${INSTANCE}-ledger-citation"
SLUG_FIX_AUTHORING="faq-doc-then-fix-sequencing-${INSTANCE}-fix-authoring"

open_phase "$SLUG_DOC_AUTHORING" "doc-authoring phase of faq-doc-then-fix-sequencing instance '${INSTANCE}' (from design/workflows/faq-doc-then-fix-sequencing.toml)"
PHASE_DOC_AUTHORING_FRESH=$?

open_phase "$SLUG_LEDGER_CITATION" "ledger-citation phase of faq-doc-then-fix-sequencing instance '${INSTANCE}' (from design/workflows/faq-doc-then-fix-sequencing.toml)"
PHASE_LEDGER_CITATION_FRESH=$?

open_phase "$SLUG_FIX_AUTHORING" "fix-authoring phase of faq-doc-then-fix-sequencing instance '${INSTANCE}' (from design/workflows/faq-doc-then-fix-sequencing.toml)"
PHASE_FIX_AUTHORING_FRESH=$?


if [ "$PHASE_LEDGER_CITATION_FRESH" -eq 1 ]; then
  out=$("$LED" work depends "$SLUG_LEDGER_CITATION" "$SLUG_DOC_AUTHORING" --type blocks-start 2>&1); rc=$?
  echo "$out"
  [ $rc -eq 0 ] || { echo "$0: REFUSED writing depends edge $SLUG_LEDGER_CITATION -> $SLUG_DOC_AUTHORING" >&2; exit 1; }
else
  echo "$SLUG_LEDGER_CITATION: skipping depends_on edge to $SLUG_DOC_AUTHORING (phase already hydrated)"
fi
if [ "$PHASE_FIX_AUTHORING_FRESH" -eq 1 ]; then
  out=$("$LED" work depends "$SLUG_FIX_AUTHORING" "$SLUG_LEDGER_CITATION" --type blocks-start 2>&1); rc=$?
  echo "$out"
  [ $rc -eq 0 ] || { echo "$0: REFUSED writing depends edge $SLUG_FIX_AUTHORING -> $SLUG_LEDGER_CITATION" >&2; exit 1; }
else
  echo "$SLUG_FIX_AUTHORING: skipping depends_on edge to $SLUG_LEDGER_CITATION (phase already hydrated)"
fi

if [ "$NO_OBLIGATE" -eq 1 ]; then
  echo "-- --no-obligate given: skipping the obligation act ((none)) --"
elif [ "0" = "1" ]; then
  echo "-- obligation act needed (row-1640 debt-surface guard): phase(s) (none) name an independent countersign --"
  echo "-- checking existing rows already written by '$OBLIGATE_OBLIGED_ACTOR' (these become retroactive debt-surface once obliged, per row-1640) --"
  HOST=$(python3 -c "import json; print(json.load(open('$DEPLOYMENT'))['host'])" 2>/dev/null)
  DB=$(python3 -c "import json; print(json.load(open('$DEPLOYMENT'))['db'])" 2>/dev/null)
  SCHEMA=$(python3 -c "import json; print(json.load(open('$DEPLOYMENT'))['schema'])" 2>/dev/null)
  if [ -n "$HOST" ] && [ -n "$DB" ] && [ -n "$SCHEMA" ]; then
    EXISTING_ROWS=$(psql -h "$HOST" -d "$DB" -tA -c \
      "SELECT count(*) FROM ${SCHEMA}.ledger WHERE actor = (SELECT id FROM ${SCHEMA}_kernel.principal WHERE name = '$OBLIGATE_OBLIGED_ACTOR');" 2>/dev/null || echo "?")
  else
    EXISTING_ROWS="?"
  fi
  echo "-- PROJECTED DEBT-SURFACE DELTA: obliging '$OBLIGATE_OBLIGED_ACTOR' will retroactively flag its $EXISTING_ROWS existing ledger row(s) as review debt (led work review-gap / led review-gap), per the row-1640 obligate-footgun teaching (retroactive, no temporal bound, self-amplifying). --"
  if [ "$ASSUME_YES" -eq 1 ]; then
    echo "-- --yes given: proceeding without interactive confirmation --"
    CONFIRMED=1
  else
    printf "Type OBLIGATE to confirm writing this obligation row, anything else to skip: "
    read -r REPLY
    if [ "$REPLY" = "OBLIGATE" ]; then CONFIRMED=1; else CONFIRMED=0; fi
  fi
  if [ "$CONFIRMED" -eq 1 ]; then
    out=$("$LED" obligate "faq-doc-then-fix-sequencing-${INSTANCE}-review" "$OBLIGATE_ASSIGNED_BY" "$OBLIGATE_OBLIGED_ACTOR" 2>&1)
    rc=$?
    if [ $rc -eq 0 ]; then
      echo "$out"
    elif printf '%s' "$out" | grep -qi "already carries an"; then
      # led obligate is ACTOR-keyed, not instance-keyed (row-1640): once 'author' carries ANY
      # obligation (from this instance or an earlier one), a second instance's hydration hits
      # this same idempotent refusal -- expected and harmless, not a per-instance defect.
      echo "$OBLIGATE_OBLIGED_ACTOR: already obliged (treated as already hydrated -- obligate is actor-keyed, covers every instance) --"
      echo "$out"
    else
      echo "$out" >&2
      exit 1
    fi
  else
    echo "-- obligation act SKIPPED (not confirmed) -- re-run with --yes or type OBLIGATE to write it. --"
  fi
else
  echo "-- no phase in this workflow names an independent countersign (J2) -- no obligation act to hydrate. --"
fi

echo "-- hydration complete for faq-doc-then-fix-sequencing instance '$INSTANCE' --"
