#!/usr/bin/env python3
"""GENERATED by tools/workflow_compile.py from design/workflows/panel-msched-resource-provisioning.toml -- do not hand-edit; recompile instead.
design/FABLE-WORKFLOW-UNIT-COMPILER-SPEC.md's driver artifact for workflow 'panel-msched-resource-provisioning'.

Executes the wave by kernel conversation: for each phase, in an order re-derived by re-polling
`led work claim` every round (never precomputed here -- the claim's own verdict is the gate,
per the governing spec's one design commitment), CLAIM (as --role-map, default 'author'; a
refusal is a BLOCKED unit, reported and moved past, never overridden), DISPATCH, CLOSE
(--review-deferred by default, or --review-bookkeeping --witness commit:<sha> when the phase's
reviews clause names a bookkeeping close -- see J4 in tools/workflow_compile.py's own docstring).

DISPATCH, per design/FABLE-ROLE-CHARTERS-AND-BRIEFS-SPEC.md (commission row 1663, replacing the
old J1 raw-prose default -- see that note in tools/workflow_compile.py's own docstring): before
claiming, the resolved principal is checked against `tools/role_charter.py show <principal>`.
CHARTED (an in-force registered charter exists): the claim proceeds and DISPATCH hands the
agent that charter text plus a freshly computed `tools/role_brief.py brief <principal>` --
"charter + brief, nothing else" (the spec's own words). UNCHARTED: REFUSED, with
role_charter's own teaching relayed verbatim, and the phase is BLOCKED-uncharted this round --
UNLESS --allow-uncharted was given, the loud escape hatch, which proceeds anyway (says so) and
falls back to the TOML's own raw authors/implements/reviews prose as DISPATCH content (the old
J1 behavior, preserved only as an explicit opt-in degraded path).

Usage:
    python3 panel-msched-resource-provisioning/drive.py --instance <token> [--led <path>] [--role-map <phase>=<principal> ...]
                              [--allow-uncharted] [--commit-witness <phase>=<sha> ...]
                              [--dry-run] [--rounds N]

--instance <token> is MANDATORY (spec Amendment, row 1660): it must be the SAME token given to
hydrate.sh for this wave -- slugs are `panel-msched-resource-provisioning-<instance>-<phase>`, so a different token drives a
DIFFERENT (or not-yet-hydrated) instance of this same TOML shape.

Exit 0 when the round budget completes (whether or not every phase closed -- BLOCKED units,
uncharted or kernel-refused alike, are an ordinary, reportable outcome, not a driver failure);
exit 1 on an unexpected kernel refusal at CLOSE time (a close, unlike a claim, should not refuse
once claimed, so that IS treated as unexpected here) or a local usage error (exit 2).
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

STEM = "panel-msched-resource-provisioning"
TOML_REL = "design/workflows/panel-msched-resource-provisioning.toml"
ROLE_CHARTER_PY = "/home/bork/w/vdc/1/autoharn/tools/role_charter.py"
ROLE_BRIEF_PY = "/home/bork/w/vdc/1/autoharn/tools/role_brief.py"

PHASES = ['provision', 'declare-resource', 'witness-schedule']
BRIEFS = {'provision': "authors: sonnet-main-session\nimplements: sonnet-main-session\nreviews: sonnet-independent-subagent\ndone: acceptance criteria (row:23) all PASS: sibling checkout present, no submodule/gitlink, editable-installed into the shared venv, import+call succeeds, this repo's own git status unaffected -- verified in row:32/34.\nlanding_zone: sibling checkout /home/bork/w/vdc/1/experience/makespan-scheduler (editable-installed into ~/w/vdc/venvs/generic); ledger rows 15/22/32/34/35.", 'declare-resource': "authors: sonnet-main-session\nimplements: sonnet-main-session\nreviews: sonnet-independent-subagent\ndone: acceptance criteria (row:37) all PASS: ledger resource: decision row with all six fields at blessed tier, honest GUIDANCE field, CLAUDE.md RESOURCES section mirrors it, ./pickup surfaces it -- verified in row:39.\nlanding_zone: ledger decision row 38 (resource: ... blessed tier) plus this repo's own CLAUDE.md RESOURCES section; ledger rows 16/36/37/39/40.", 'witness-schedule': 'authors: sonnet-main-session\nimplements: sonnet-main-session\nreviews: sonnet-independent-subagent\ndone: acceptance criteria (row:43) all PASS: jobs.json models the real decomposition against a genuine shared resource, the tool is actually invoked, the result is ledgered honestly noting agreement/disagreement with the real work_depends precedence, the schedule artifact is saved and cited -- verified in row:44.\nlanding_zone: scratch/msched-witness/schedule.json, committed to the panel repo as cited evidence; ledger rows 17/42/43/44/46.'}
BOOKKEEPING_PHASES = []
DEFAULT_ACTOR = "author"
INSTANCE_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def run_led(led: str, args: list[str], actor: str) -> tuple[int, str]:
    proc = subprocess.run([led] + args, capture_output=True, text=True,
                           env={**os.environ, "LED_ACTOR": actor})
    return proc.returncode, (proc.stdout + proc.stderr).strip()


def check_charter(led: str, principal: str) -> tuple[int, str]:
    proc = subprocess.run([sys.executable, ROLE_CHARTER_PY, "show", principal, "--led", led],
                           capture_output=True, text=True)
    return proc.returncode, (proc.stdout + proc.stderr).strip()


def fetch_brief(led: str, principal: str) -> tuple[int, str]:
    proc = subprocess.run([sys.executable, ROLE_BRIEF_PY, "brief", principal, "--led", led],
                           capture_output=True, text=True)
    return proc.returncode, (proc.stdout + proc.stderr).strip()


def parse_kv(pairs: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for pair in pairs:
        if "=" not in pair:
            print(f"drive.py: '{pair}' is not <key>=<value>", file=sys.stderr)
            sys.exit(2)
        k, v = pair.split("=", 1)
        out[k] = v
    return out


def main(argv: list[str]) -> int:
    # legacy-led-retirement pass (row 1149): NOT flipped to "./led" (see hydrate.sh's comment) --
    # this value also feeds `fetch_brief`'s `--led` into role_brief.py, whose parsers still
    # silently misparse served output (disclosed, still-open gap) -- out of this pass's scope.
    led = "./legacy/led"
    instance: str | None = None
    role_map: dict[str, str] = {}
    allow_uncharted = False
    commit_witness: dict[str, str] = {}
    dry_run = False
    rounds = len(PHASES) + 1

    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--led":
            led = argv[i + 1]; i += 2
        elif a == "--instance":
            instance = argv[i + 1]; i += 2
        elif a == "--role-map":
            role_map.update(parse_kv([argv[i + 1]])); i += 2
        elif a == "--allow-uncharted":
            allow_uncharted = True; i += 1
        elif a == "--commit-witness":
            commit_witness.update(parse_kv([argv[i + 1]])); i += 2
        elif a == "--dry-run":
            dry_run = True; i += 1
        elif a == "--rounds":
            rounds = int(argv[i + 1]); i += 2
        else:
            print(f"drive.py: unrecognized argument '{a}'", file=sys.stderr)
            return 2

    # --instance is MANDATORY and allowlist-validated BEFORE anything else runs (same
    # interpreter-boundary discipline as hydrate.sh's own check -- this token is concatenated
    # into every slug this run claims/closes).
    if not instance:
        print("drive.py: REFUSED -- --instance <token> is mandatory (spec Amendment, row 1660).",
              file=sys.stderr)
        return 2
    if not INSTANCE_TOKEN_RE.match(instance):
        print(f"drive.py: REFUSED -- --instance '{instance}' is not [A-Za-z0-9_-]+ "
              f"(interpreter-boundary discipline: this token is concatenated into every slug "
              f"this run claims/closes).", file=sys.stderr)
        return 2

    for phase in BOOKKEEPING_PHASES:
        if phase not in commit_witness:
            print(f"drive.py: REFUSED locally (not a kernel refusal) -- phase '{phase}' "
                  f"closes --review-bookkeeping and needs --commit-witness {phase}=<sha>, "
                  f"none given.", file=sys.stderr)
            return 2

    print(f"-- driving workflow '{STEM}' instance '{instance}' (source {TOML_REL}) via {led} --")

    closed: set[str] = set()
    for round_no in range(1, rounds + 1):
        made_progress = False
        for phase in PHASES:
            slug = f"{STEM}-{instance}-{phase}"
            if slug in closed:
                continue
            actor = role_map.get(phase, DEFAULT_ACTOR)
            print(f"round {round_no}: phase '{phase}' -> principal '{actor}' (--role-map)")

            charter_rc, charter_out = check_charter(led, actor)
            if charter_rc != 0:
                if not allow_uncharted:
                    print(
                        f"  REFUSED (uncharted) -- '{actor}' has no in-force registered "
                        f"charter; phase '{phase}' is BLOCKED-uncharted this round. Register "
                        f"one (python3 tools/role_charter.py register {actor} <path>) or pass "
                        f"--allow-uncharted to proceed anyway (loud escape hatch, not silent). "
                        f"role_charter's own teaching, verbatim:\n{charter_out}"
                    )
                    continue
                print(
                    f"  -- --allow-uncharted: proceeding with UNCHARTED principal '{actor}' "
                    f"for phase '{phase}' -- falling back to the TOML's own raw prose brief "
                    f"(the pre-row-1663 J1 default). role_charter said:\n{charter_out}"
                )
                dispatch_text = BRIEFS.get(phase, "")
            else:
                brief_rc, brief_out = fetch_brief(led, actor)
                if brief_rc == 0:
                    dispatch_text = charter_out + "\n\n" + brief_out
                else:
                    dispatch_text = (
                        charter_out + f"\n\n(role_brief FAILED, rc={brief_rc}, relayed "
                        f"verbatim rather than silently omitted:\n{brief_out})"
                    )

            print(f"round {round_no}: attempting claim of '{slug}' as '{actor}' ...")
            if dry_run:
                print(f"  (dry-run) would run: LED_ACTOR={actor} {led} work claim {slug}")
                continue
            claim_rc, claim_out = run_led(led, ["work", "claim", slug], actor)
            if claim_rc != 0:
                print(f"  BLOCKED -- kernel refusal (verbatim):\n{claim_out}")
                continue
            print(f"  claimed: {claim_out}")
            print(f"  DISPATCH -- charter+brief for '{phase}' (principal '{actor}'):\n{dispatch_text}")
            if phase in BOOKKEEPING_PHASES:
                close_args = ["work", "close", slug, "shipped", "--review-bookkeeping",
                              "--witness", f"commit:{commit_witness[phase]}"]
            else:
                close_args = ["work", "close", slug, "shipped", "--review-deferred",
                              "--witness", f"unit:{slug}"]
            close_rc, close_out = run_led(led, close_args, actor)
            if close_rc != 0:
                print(f"  CLOSE REFUSED -- kernel refusal (verbatim):\n{close_out}",
                      file=sys.stderr)
                return 1
            print(f"  closed: {close_out}")
            closed.add(slug)
            made_progress = True
        if len(closed) == len(PHASES) or (not made_progress and not dry_run):
            break

    print(f"-- drive complete: {len(closed)}/{len(PHASES)} phase(s) closed --")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
