#!/usr/bin/env python3
"""GENERATED by tools/workflow_compile.py from design/workflows/panel-msched-resource-provisioning.toml -- do not hand-edit; recompile instead.
design/FABLE-WORKFLOW-UNIT-COMPILER-SPEC.md's driver artifact for workflow 'panel-msched-resource-provisioning'.

Executes the wave by kernel conversation: for each phase, in an order re-derived by re-polling
`led work claim` every round (never precomputed here -- the claim's own verdict is the gate,
per the governing spec's one design commitment), CLAIM (as --role-map, default 'author'; a
refusal is a BLOCKED unit, reported and moved past, never overridden), DISPATCH, CLOSE
(--review-deferred by default, or --review-bookkeeping --witness commit:<sha> when the phase's
reviews clause names a bookkeeping close -- see J4 in tools/workflow_compile.py's own docstring).

DISPATCH, per design/FABLE-ROLE-CHARTERS-AND-BRIEFS-SPEC.md (commission row 1663, replacing the
old J1 raw-prose default -- see that note in tools/workflow_compile.py's own docstring): before
claiming, the resolved principal is checked against `tools/role_charter.py show <principal>`.
CHARTED (an in-force registered charter exists): the claim proceeds and DISPATCH hands the
agent that charter text plus a freshly computed `tools/role_brief.py brief <principal>` --
"charter + brief, nothing else" (the spec's own words). UNCHARTED: REFUSED, with
role_charter's own teaching relayed verbatim, and the phase is BLOCKED-uncharted this round --
UNLESS --allow-uncharted was given, the loud escape hatch, which proceeds anyway (says so) and
falls back to the TOML's own raw authors/implements/reviews prose as DISPATCH content (the old
J1 behavior, preserved only as an explicit opt-in degraded path).

CWD ASSUMPTION: invoked from THIS repo's own root, `led`'s AUTOHARN_ROOT convention -- --led's
default ("libexec/autoharn/led") is relative to THAT cwd; elsewhere pass an explicit --led
<path>, or the driver refuses loudly (see LedUnusable below) rather than silently misreporting
every phase as an ordinary uncharted/kernel refusal.

Usage:
    python3 panel-msched-resource-provisioning/drive.py --instance <token> [--led <path>] [--role-map <phase>=<principal> ...]
                              [--allow-uncharted] [--commit-witness <phase>=<sha> ...]
                              [--dry-run] [--rounds N]

--instance <token> is MANDATORY (spec Amendment, row 1660): it must be the SAME token given to
hydrate.sh for this wave -- slugs are `panel-msched-resource-provisioning-<instance>-<phase>`, so a different token drives a
DIFFERENT (or not-yet-hydrated) instance of this same TOML shape.

Exit 0 when the round budget completes (whether or not every phase closed -- BLOCKED units,
uncharted or kernel-refused alike, are an ordinary, reportable outcome, not a driver failure);
exit 1 on an unexpected kernel refusal at CLOSE time (a close, unlike a claim, should not refuse
once claimed, so that IS treated as unexpected here), on a LedUnusable condition (--led itself
cannot be used at all -- empty, malformed quoting, or exec failure, e.g. a wrong CWD relative to
the default; see LedUnusable below), or a local usage error (exit 2).
"""
from __future__ import annotations

import os
import re
import shlex
import subprocess
import sys

STEM = "panel-msched-resource-provisioning"
TOML_REL = "design/workflows/panel-msched-resource-provisioning.toml"
ROLE_CHARTER_PY = "/home/bork/w/vdc/1/autoharn/tools/role_charter.py"
ROLE_BRIEF_PY = "/home/bork/w/vdc/1/autoharn/tools/role_brief.py"

PHASES = ['provision', 'declare-resource', 'witness-schedule']
BRIEFS = {'provision': "authors: sonnet-main-session\nimplements: sonnet-main-session\nreviews: sonnet-independent-subagent\ndone: acceptance criteria (row:23) all PASS: sibling checkout present, no submodule/gitlink, editable-installed into the shared venv, import+call succeeds, this repo's own git status unaffected -- verified in row:32/34.\nlanding_zone: sibling checkout /home/bork/w/vdc/1/experience/makespan-scheduler (editable-installed into ~/w/vdc/venvs/generic); ledger rows 15/22/32/34/35.", 'declare-resource': "authors: sonnet-main-session\nimplements: sonnet-main-session\nreviews: sonnet-independent-subagent\ndone: acceptance criteria (row:37) all PASS: ledger resource: decision row with all six fields at blessed tier, honest GUIDANCE field, CLAUDE.md RESOURCES section mirrors it, ./pickup surfaces it -- verified in row:39.\nlanding_zone: ledger decision row 38 (resource: ... blessed tier) plus this repo's own CLAUDE.md RESOURCES section; ledger rows 16/36/37/39/40.", 'witness-schedule': 'authors: sonnet-main-session\nimplements: sonnet-main-session\nreviews: sonnet-independent-subagent\ndone: acceptance criteria (row:43) all PASS: jobs.json models the real decomposition against a genuine shared resource, the tool is actually invoked, the result is ledgered honestly noting agreement/disagreement with the real work_depends precedence, the schedule artifact is saved and cited -- verified in row:44.\nlanding_zone: scratch/msched-witness/schedule.json, committed to the panel repo as cited evidence; ledger rows 17/42/43/44/46.'}
BOOKKEEPING_PHASES = []
DEFAULT_ACTOR = "author"
INSTANCE_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]+$")

# CONFIRMING-REVIEW FIX ROUND, findings 1+2 (2026-07-26). LED_UNUSABLE_MARKER is emitted (as a
# prefix on the returned error text) by every conversion of a --led-itself-is-broken condition to
# an ordinary (rc, out) tuple below AND by tools/role_charter.py's/tools/role_brief.py's own
# run_led (same marker, same reasoning) -- it lets check_charter/fetch_brief tell "role_charter.py
# could not use --led at all" (a wrong-deployment/config problem: led binary not found relative to
# this CWD, an empty --led value, or malformed shell quoting) apart from an ORDINARY refusal `led`
# or role_charter.py itself might emit (e.g. "no registered charter") -- the two must never be
# conflated, per finding 1: a wrong CWD used to read as an honest "REFUSED (uncharted)" per phase,
# exit 0, indistinguishable from a real uncharted principal.
LED_UNUSABLE_MARKER = "LED-UNUSABLE:"


class LedUnusable(Exception):
    """Raised when the resolved --led value cannot be used AT ALL: empty/whitespace (would
    execute this call's own next argv token as the program), malformed shell quoting (shlex.split
    raises), or exec failure (led binary not found -- frequently a wrong CWD, since --led's
    default is relative to the repo root drive.py is documented to run from). This is a
    wrong-deployment/config problem, never an ordinary kernel or charter refusal -- caught exactly
    once in main(), which stops the WHOLE drive immediately with a loud, teaching, nonzero-exit
    refusal naming the --led value tried, the CWD, and the CWD assumption, rather than looping
    over every remaining phase reporting a misleading per-phase BLOCKED-uncharted/refused
    outcome (finding 1's exact failure shape) or dying as a raw traceback (the --allow-uncharted
    path's prior failure shape, finding 1's other half)."""


def _split_led(led: str) -> list[str]:
    """Shared by run_led/check_charter/fetch_brief: refuse an empty/whitespace --led loudly
    (shlex.split('') is [], which would silently execute this call's OWN next argv token as the
    program -- a config error, not a kernel fact) and convert a shlex.split ValueError (malformed
    shell quoting, e.g. an unterminated quote) to the same LedUnusable class rather than an
    uncaught traceback (finding 2)."""
    if not led.strip():
        raise LedUnusable(
            f"drive.py: REFUSED -- --led value is empty/whitespace -- refusing rather than "
            f"executing this call's own next argv token as the program (shlex.split('') is [])."
        )
    try:
        return shlex.split(led)
    except ValueError as exc:
        raise LedUnusable(
            f"drive.py: REFUSED -- --led value {led!r} is malformed shell quoting: {exc}"
        ) from exc


def run_led(led: str, args: list[str], actor: str) -> tuple[int, str]:
    led_argv = _split_led(led)  # multi-token --led; raises LedUnusable on empty/malformed (finding 2)
    try:
        proc = subprocess.run(led_argv + args, capture_output=True, text=True,
                               env={**os.environ, "LED_ACTOR": actor})
    except OSError as exc:
        raise LedUnusable(
            f"drive.py: REFUSED -- could not execute led {led!r} (cwd={os.getcwd()}): {exc}. "
            f"This driver assumes it is invoked from the repo root (led's AUTOHARN_ROOT "
            f"convention -- see this module's own docstring 'CWD ASSUMPTION' note); run it from "
            f"there, or pass an explicit --led <path> that resolves from wherever you are."
        ) from exc
    return proc.returncode, (proc.stdout + proc.stderr).strip()


def check_charter(led: str, principal: str) -> tuple[int, str]:
    proc = subprocess.run([sys.executable, ROLE_CHARTER_PY, "show", principal, "--led", led],
                           capture_output=True, text=True)
    out = (proc.stdout + proc.stderr).strip()
    if proc.returncode != 0 and LED_UNUSABLE_MARKER in out:
        # role_charter.py's OWN run_led hit the identical --led-is-broken condition (empty,
        # malformed quoting, or exec failure) while checking this principal -- NOT a "no
        # registered charter" answer. Propagate loudly rather than letting the caller read this
        # nonzero rc as an ordinary uncharted refusal (finding 1's exact failure shape).
        raise LedUnusable(
            f"drive.py: REFUSED -- role_charter.py could not use --led {led!r} while checking "
            f"principal '{principal}' (cwd={os.getcwd()}) -- a wrong-deployment/config problem, "
            f"never an ordinary 'uncharted' outcome; run from the repo root (led's AUTOHARN_ROOT "
            f"convention -- see this module's own docstring 'CWD ASSUMPTION' note), or pass an "
            f"explicit --led <path> that resolves from wherever you are. role_charter's own "
            f"text, verbatim:\n{out}"
        )
    return proc.returncode, out


def fetch_brief(led: str, principal: str) -> tuple[int, str]:
    proc = subprocess.run([sys.executable, ROLE_BRIEF_PY, "brief", principal, "--led", led],
                           capture_output=True, text=True)
    out = (proc.stdout + proc.stderr).strip()
    if proc.returncode != 0 and LED_UNUSABLE_MARKER in out:
        # same class as check_charter's own check above -- reached only when check_charter (using
        # the SAME --led value) already succeeded, so this would be a surprising, independent
        # led-unusable condition; propagated the same way rather than silently downgraded to a
        # generic "role_brief FAILED" line (this hazard is in reach of the identical fix).
        raise LedUnusable(
            f"drive.py: REFUSED -- role_brief.py could not use --led {led!r} while fetching "
            f"principal '{principal}''s brief (cwd={os.getcwd()}) -- a wrong-deployment/config "
            f"problem, never an ordinary brief-fetch failure. role_brief's own text, "
            f"verbatim:\n{out}"
        )
    return proc.returncode, out


def parse_kv(pairs: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for pair in pairs:
        if "=" not in pair:
            print(f"drive.py: '{pair}' is not <key>=<value>", file=sys.stderr)
            sys.exit(2)
        k, v = pair.split("=", 1)
        out[k] = v
    return out


def main(argv: list[str]) -> int:
    # Flipped to served "./led" (row 1307/1308, 2026-07-26): "./legacy/led" is a pure exit-1
    # stub, so this default made check_charter/fetch_brief fail unconditionally, UNCHARTED
    # regardless of any real charter. Prior rationale (role_brief.py misparsing) is dead too: 417b200 made it refuse loudly.
    led = "libexec/autoharn/led"  # flipped again 2026-07-26 (finding 1): bare ./led also retired
    instance: str | None = None
    role_map: dict[str, str] = {}
    allow_uncharted = False
    commit_witness: dict[str, str] = {}
    dry_run = False
    rounds = len(PHASES) + 1

    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--led":
            led = argv[i + 1]; i += 2
        elif a == "--instance":
            instance = argv[i + 1]; i += 2
        elif a == "--role-map":
            role_map.update(parse_kv([argv[i + 1]])); i += 2
        elif a == "--allow-uncharted":
            allow_uncharted = True; i += 1
        elif a == "--commit-witness":
            commit_witness.update(parse_kv([argv[i + 1]])); i += 2
        elif a == "--dry-run":
            dry_run = True; i += 1
        elif a == "--rounds":
            rounds = int(argv[i + 1]); i += 2
        else:
            print(f"drive.py: unrecognized argument '{a}'", file=sys.stderr)
            return 2

    # --instance is MANDATORY and allowlist-validated BEFORE anything else runs (same
    # interpreter-boundary discipline as hydrate.sh's own check -- this token is concatenated
    # into every slug this run claims/closes).
    if not instance:
        print("drive.py: REFUSED -- --instance <token> is mandatory (spec Amendment, row 1660).",
              file=sys.stderr)
        return 2
    if not INSTANCE_TOKEN_RE.match(instance):
        print(f"drive.py: REFUSED -- --instance '{instance}' is not [A-Za-z0-9_-]+ "
              f"(interpreter-boundary discipline: this token is concatenated into every slug "
              f"this run claims/closes).", file=sys.stderr)
        return 2

    for phase in BOOKKEEPING_PHASES:
        if phase not in commit_witness:
            print(f"drive.py: REFUSED locally (not a kernel refusal) -- phase '{phase}' "
                  f"closes --review-bookkeeping and needs --commit-witness {phase}=<sha>, "
                  f"none given.", file=sys.stderr)
            return 2

    print(f"-- driving workflow '{STEM}' instance '{instance}' (source {TOML_REL}) via {led} --")

    closed: set[str] = set()
    try:
        for round_no in range(1, rounds + 1):
            made_progress = False
            for phase in PHASES:
                slug = f"{STEM}-{instance}-{phase}"
                if slug in closed:
                    continue
                actor = role_map.get(phase, DEFAULT_ACTOR)
                print(f"round {round_no}: phase '{phase}' -> principal '{actor}' (--role-map)")

                charter_rc, charter_out = check_charter(led, actor)
                if charter_rc != 0:
                    if not allow_uncharted:
                        print(
                            f"  REFUSED (uncharted) -- '{actor}' has no in-force registered "
                            f"charter; phase '{phase}' is BLOCKED-uncharted this round. Register "
                            f"one (python3 tools/role_charter.py register {actor} <path>) or pass "
                            f"--allow-uncharted to proceed anyway (loud escape hatch, not silent). "
                            f"role_charter's own teaching, verbatim:\n{charter_out}"
                        )
                        continue
                    print(
                        f"  -- --allow-uncharted: proceeding with UNCHARTED principal '{actor}' "
                        f"for phase '{phase}' -- falling back to the TOML's own raw prose brief "
                        f"(the pre-row-1663 J1 default). role_charter said:\n{charter_out}"
                    )
                    dispatch_text = BRIEFS.get(phase, "")
                else:
                    brief_rc, brief_out = fetch_brief(led, actor)
                    if brief_rc == 0:
                        dispatch_text = charter_out + "\n\n" + brief_out
                    else:
                        dispatch_text = (
                            charter_out + f"\n\n(role_brief FAILED, rc={brief_rc}, relayed "
                            f"verbatim rather than silently omitted:\n{brief_out})"
                        )

                print(f"round {round_no}: attempting claim of '{slug}' as '{actor}' ...")
                if dry_run:
                    print(f"  (dry-run) would run: LED_ACTOR={actor} {led} work claim {slug}")
                    continue
                claim_rc, claim_out = run_led(led, ["work", "claim", slug], actor)
                if claim_rc != 0:
                    print(f"  BLOCKED -- kernel refusal (verbatim):\n{claim_out}")
                    continue
                print(f"  claimed: {claim_out}")
                print(f"  DISPATCH -- charter+brief for '{phase}' (principal '{actor}'):\n{dispatch_text}")
                if phase in BOOKKEEPING_PHASES:
                    close_args = ["work", "close", slug, "shipped", "--review-bookkeeping",
                                  "--witness", f"commit:{commit_witness[phase]}"]
                else:
                    close_args = ["work", "close", slug, "shipped", "--review-deferred",
                                  "--witness", f"unit:{slug}"]
                close_rc, close_out = run_led(led, close_args, actor)
                if close_rc != 0:
                    print(f"  CLOSE REFUSED -- kernel refusal (verbatim):\n{close_out}",
                          file=sys.stderr)
                    return 1
                print(f"  closed: {close_out}")
                closed.add(slug)
                made_progress = True
            if len(closed) == len(PHASES) or (not made_progress and not dry_run):
                break
    except LedUnusable as exc:
        # findings 1+2: --led itself is unusable (wrong CWD, empty value, or malformed quoting)
        # -- a wrong-deployment/config problem, never conflated with an ordinary per-phase
        # uncharted/kernel refusal. Stop the WHOLE drive here, loudly, nonzero exit -- never
        # silently reported as "REFUSED (uncharted)" (exit 0) and never a raw traceback.
        print(str(exc), file=sys.stderr)
        return 1

    print(f"-- drive complete: {len(closed)}/{len(PHASES)} phase(s) closed --")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
