#!/usr/bin/env python3
# >>> PROVENANCE-STAMP >>> (auto; tools/hooks/stamp_provenance.py — do not hand-edit)
#   first-seen : 2026-07-21T22:14:17Z
#   last-change: 2026-07-21T22:14:17Z
#   contributors: 43f77bff/main
# <<< PROVENANCE-STAMP <<<

"""tools/setup_tui/daemon_scaffold.py -- feature-scaffold DATA for the daemons a wizard run
selects (design/FABLE-SETUP-TUI-CHECKLIST-SPLIT-SPEC.md §3): the otelcol-config.yaml content and
the generated `<dest>/start-daemons` script body. Kept as its OWN module, separate from
screens.py and commit_executor.py -- the spec's own instruction: "the config template's content
belongs to the feature's scaffold data, not to screens.py (compose with the ... 'data is not
code' amendment ...; do not add new embedded prose blocks)". `feature_facts.py` is this
package's existing precedent for a data-owning module screens.py renders FROM rather than
carries inline (its own module docstring: "no screen carries a facts string of its own") --
this module is the same posture applied to file CONTENT rather than a facts line.

Nothing here performs an effect -- every function is a pure string builder over a
`tools.setup_tui.plan.DaemonSelection` list. `commit_executor.py` is the ONLY caller that turns
this module's output into a real file (through the ordinary `WriteAct`/`runner.write_file`
choke point, never a second write path -- ADR-0012 P1).

STDIO HYGIENE IN THE GENERATED SCRIPT (mirrors `runner.start_background`'s own fix, module
docstring there): every daemon this script starts gets `< /dev/null` (no stdin claimed from the
operator's shell) and its stdout+stderr redirected to a per-daemon LOG FILE under
`<dest>/.setup-tui-daemon-logs/`, never left attached to the script's own controlling terminal --
the same class of hazard (a chatty daemon's own stdout filling an unread pipe/inherited fd) the
commission's field observation g named, applied here to the SCRIPT's own children rather than
this Python process's.

IDEMPOTENCE (spec §3 point 1: "a daemon already up is reported, not double-started"): a
PID-FILE check under `<dest>/.setup-tui-daemon-pids/`, independent of `health_probe` (which is
a network/process probe the wizard's own Python-side end-of-run sweep uses, a DIFFERENT concern
-- the script's own idempotence must work even for a daemon with no live-checkable health signal
at all, e.g. otel-watch, so it cannot depend on `health_probe` being non-empty).

Lazy imports are banned (CLAUDE.md, 2026-07-02): every import here is top of file."""
from __future__ import annotations

import shlex

from tools.setup_tui.plan import DaemonSelection

# --------------------------------------------------------------------------------------------
# otelcol-config.yaml -- the prerequisite file the printed otelcol start line references
# (backflow finding 3's own root cause: the config was never written, so the printed
# "otelcol-contrib --config otelcol-config.yaml" line pointed at nothing).
# --------------------------------------------------------------------------------------------

OTELCOL_CONFIG_TEMPLATE = """\
# Generated by tools/setup_tui (design/FABLE-SETUP-TUI-CHECKLIST-SPLIT-SPEC.md \xa73) --
# localhost-only OTLP receiver (design/FABLE-OTEL-SENTRY-SPEC.md's own deployment-shape-A
# record: 127.0.0.1:4317 gRPC, file exporter), plus a health_check extension so this world's
# start-daemons script and the wizard's own end-of-run verification sweep have a real liveness
# signal to probe rather than guessing from process existence alone.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317

exporters:
  file:
    path: {export_path}

extensions:
  health_check:
    endpoint: 127.0.0.1:13133

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [file]
    traces:
      receivers: [otlp]
      exporters: [file]
"""

OTELCOL_HEALTH_URL = "http://127.0.0.1:13133/"


def otelcol_config_content(export_path: str) -> str:
    """The real content of `<dest>/otelcol-config.yaml` -- a pure format of the template above
    over the one caller-supplied value (where this world's own JSONL export lands)."""
    return OTELCOL_CONFIG_TEMPLATE.format(export_path=export_path)


# --------------------------------------------------------------------------------------------
# <dest>/start-daemons -- the generated script (maintainer's g.1 commission, verbatim scope:
# "a daemon collection script depending on selected options that start all relevant daemons and
# stores into the project folder").
# --------------------------------------------------------------------------------------------

_SCRIPT_HEADER = """\
#!/usr/bin/env bash
# Generated by tools/setup_tui -- design/FABLE-SETUP-TUI-CHECKLIST-SPLIT-SPEC.md \xa73.
# Starts every daemon this wizard run selected. Idempotent (a daemon already up, per its own
# pidfile, is reported rather than double-started); refuses PER DAEMON, naming the missing
# artifact, when a prerequisite is absent (ADR-0002 rung 3 -- one daemon's refusal never blocks
# a sibling's start). Do not hand-edit -- re-run the wizard (or edit its plan) instead; a
# hand-edit here is silently overwritten the next time this script is regenerated.
set -u
DEST={dest_quoted}
PIDDIR="$DEST/.setup-tui-daemon-pids"
LOGDIR="$DEST/.setup-tui-daemon-logs"
mkdir -p "$PIDDIR" "$LOGDIR"
STATUS=0
"""

_SCRIPT_FOOTER = """
exit "$STATUS"
"""


def _sanitize_tag(name: str) -> str:
    """A filesystem/variable-safe tag for `name` -- alphanumerics kept, everything else folded
    to `_`. Used only for pidfile/logfile BASENAMES (never spliced into a command line as
    program text -- ADR-0000's 2026-07-18 amendment), so a collision-free bijection is not
    required, only a safe filename; `render_start_daemons_script` is the only caller and it
    always has the full `DaemonSelection` list in hand to eyeball for accidental collisions."""
    return "".join(c if c.isalnum() else "_" for c in name) or "daemon"


def _daemon_block(d: DaemonSelection) -> str:
    tag = _sanitize_tag(d.name)
    cwd = d.cwd or "$DEST"
    argv_quoted = " ".join(shlex.quote(a) for a in d.argv)
    lines = [
        f'echo "--- {d.name} ---"',
    ]
    if d.prerequisite:
        prereq_quoted = shlex.quote(d.prerequisite)
        lines += [
            f"if [ ! -e {prereq_quoted} ]; then",
            f'  echo "REFUSED: {d.name} -- missing prerequisite: {d.prerequisite}" >&2',
            '  STATUS=1',
            "else",
        ]
        indent = "  "
    else:
        indent = ""
    lines += [
        f'{indent}PIDFILE="$PIDDIR/{tag}.pid"',
        f'{indent}if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null; then',
        f'{indent}  echo "{d.name}: already up (pid $(cat "$PIDFILE"))"',
        f"{indent}else",
        f'{indent}  ( cd {shlex.quote(cwd)} && exec {argv_quoted} ) '
        f'< /dev/null > "$LOGDIR/{tag}.log" 2>&1 &',
        f'{indent}  echo $! > "$PIDFILE"',
        f'{indent}  echo "{d.name}: started (pid $(cat "$PIDFILE")), log: $LOGDIR/{tag}.log"',
        f"{indent}fi",
    ]
    if d.prerequisite:
        lines.append("fi")
    lines.append("")
    return "\n".join(lines)


def render_start_daemons_script(daemons: "list[DaemonSelection]", dest: str) -> str:
    """The full `<dest>/start-daemons` text -- a pure function of the accumulated
    `Plan.daemons` list and `dest`, called ONCE, from `commit_executor.execute` (§3's "derive,
    at commit time"). Empty `daemons` is never called with (commit_executor only synthesizes
    this entry when `plan.daemons` is non-empty) but would still render a syntactically valid,
    no-op script if it somehow were -- never a crash on the boundary condition."""
    parts = [_SCRIPT_HEADER.format(dest_quoted=shlex.quote(dest))]
    for d in daemons:
        parts.append(_daemon_block(d))
    parts.append(_SCRIPT_FOOTER)
    return "\n".join(parts)
