#!/usr/bin/env python3
"""doc_table_generation — wires `tools/experiments/typed_table.py`'s constructor into the
authoring flow as the ONE home for a constructed table's content (ADR-0012 P1: "every fact has
exactly one home ... never hand-copied as a literal or re-encoded in a second place"; work item
`typed-table-ssot-integration`, the mandated follow-up to the typed-table-constructor-experiment
ADOPTION, maintainer 2026-07-14).

THE INTEGRATION SHAPE CHOSEN, and why. The experiment note itself
(`vestigial_documentation/design/ORCH-TYPED-TABLE-EXPERIMENT.md`, "The source-of-truth question"
section) names two candidate shapes and explicitly does not choose between them: (a) an in-doc
fenced code block AS the call site, checked hash-equal against the rendered table beneath it, or
(b) a call site living in a separate tracked `.py` file, with the doc's table regenerated by a
script and checked for drift pre-commit. This module takes (b) — the SMALLER of the two, per this
work item's own instruction to pick the smallest one-home integration when the note leaves the
seam open: it needs no new doc-authoring convention (a fenced Python block sitting inside prose,
a format every doc-reading tool and every future author would first have to learn) and it changes
nothing about how a table LOOKS once rendered — only two new HTML-comment anchor lines bracket
it, the same idiom this corpus already uses for the constructor's own provenance comment
(`typed_table.Table.render()`) and for `doc_attestation_presence.py`'s waiver token.

REGISTRY below is the one place a table's builder function is named — the "call site is the
SSOT" contract made concrete. A doc registered here never carries hand-authored table text
again: `--check` fails (drift, RED) the instant the doc's on-disk bytes between the anchors
diverge from what the registered builder renders TODAY; `--write` is the only sanctioned way to
update the doc's copy. A drifted hand-edit between the anchors is therefore structurally
impossible to land clean — the two-home hazard the experiment note named as unresolved is closed
for every doc that opts in by being listed here.

ANCHOR CONVENTION (new, this module): a registered table's region in its doc is delimited by
    <!-- typed-table:BEGIN id=<table_id> -->
    ...generated content, byte-for-byte tools/experiments/typed_table.py output...
    <!-- typed-table:END id=<table_id> -->
Both lines are literal HTML comments on their own line; everything strictly between them
(exclusive of the marker lines) is replaced wholesale by `--write` and diffed wholesale by
`--check`. A doc with no matching BEGIN/END pair for a registered id is a hard error (the
registry claims a home that does not exist in the doc — a configuration mistake, not a drift).

WHAT THIS DOES NOT CLAIM: registering a table here does not make its `inhabits=` articulations
TRUE (typed_table.py's own honest limit, unchanged); it only makes the doc's copy IMPOSSIBLE to
hand-edit into disagreement with its call site without the drift check catching it.

Lazy imports are banned (CLAUDE.md, 2026-07-02): everything below imports at module load.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
_EXPERIMENTS_DIR = str(REPO_ROOT / "tools" / "experiments")
if _EXPERIMENTS_DIR not in sys.path:
    sys.path.insert(0, _EXPERIMENTS_DIR)
from typed_table import Table  # noqa: E402

_TOOLS_DIR = str(REPO_ROOT / "tools")
if _TOOLS_DIR not in sys.path:
    sys.path.insert(0, _TOOLS_DIR)
import doc_table_registry  # noqa: E402 — the actual call sites (builder functions), kept in
# their own file rather than this one so REGISTRY's *shape* (this module) and its *content*
# (the per-table builders) are separately reviewable — the same split typed_table.py's demo_*
# functions already model, just promoted from demo status to a real registered home.

REGISTRY = doc_table_registry.REGISTRY


def _anchor_lines(table_id: str) -> tuple:
    return (f"<!-- typed-table:BEGIN id={table_id} -->",
            f"<!-- typed-table:END id={table_id} -->")


def _locate(lines: list, begin: str, end: str, doc_rel: str, table_id: str) -> tuple:
    """Return (begin_idx, end_idx) of the two anchor lines in `lines` (list of lines, no
    trailing newlines). Refuses — loudly, ADR-0002 — rather than guessing, on: anchor absent,
    duplicated, or out of order."""
    begin_idxs = [i for i, l in enumerate(lines) if l.strip() == begin]
    end_idxs = [i for i, l in enumerate(lines) if l.strip() == end]
    if not begin_idxs:
        raise ValueError(f"{doc_rel}: no BEGIN anchor for registered table {table_id!r} "
                          f"(expected line {begin!r}) — register removed the anchor, or the "
                          f"table was never wired in; run --write once to create it, or fix "
                          f"the registry entry")
    if not end_idxs:
        raise ValueError(f"{doc_rel}: no END anchor for registered table {table_id!r} "
                          f"(expected line {end!r})")
    if len(begin_idxs) > 1 or len(end_idxs) > 1:
        raise ValueError(f"{doc_rel}: duplicate anchor for table {table_id!r} "
                          f"(BEGIN at lines {begin_idxs}, END at lines {end_idxs})")
    b, e = begin_idxs[0], end_idxs[0]
    if e <= b:
        raise ValueError(f"{doc_rel}: END anchor for {table_id!r} appears before (or at) BEGIN "
                          f"— anchors out of order")
    return b, e


def render(table_id: str) -> str:
    """The rendered, current bytes for one registered table — always freshly computed from its
    builder, never cached: this IS the one-home guarantee (ADR-0012 P1) made an executable
    function rather than a claim."""
    if table_id not in REGISTRY:
        raise KeyError(f"no such registered table id: {table_id!r} (known: "
                        f"{sorted(REGISTRY)})")
    entry = REGISTRY[table_id]
    built = entry["builder"]()
    rendered = built.render() if isinstance(built, Table) else built
    return rendered.rstrip("\n")


def _region(doc_path: Path, table_id: str) -> tuple:
    """(lines, begin_idx, end_idx, current_region_text) for one registered doc/table pair."""
    doc_rel = str(doc_path.resolve().relative_to(REPO_ROOT))
    text = doc_path.read_text(encoding="utf-8")
    lines = text.split("\n")
    begin, end = _anchor_lines(table_id)
    b, e = _locate(lines, begin, end, doc_rel, table_id)
    current = "\n".join(lines[b + 1:e])
    return lines, b, e, current


def check(table_ids: "list | None" = None) -> list:
    """Return a list of human-readable drift findings, empty if every named (or every
    registered) table's doc region matches its builder's current output exactly."""
    ids = table_ids or sorted(REGISTRY)
    findings = []
    for tid in ids:
        entry = REGISTRY[tid]
        doc_path = REPO_ROOT / entry["doc"]
        if not doc_path.exists():
            findings.append(f"{tid}: registered doc {entry['doc']} does not exist")
            continue
        try:
            _lines, _b, _e, current = _region(doc_path, tid)
        except ValueError as exc:
            findings.append(str(exc))
            continue
        wanted = render(tid)
        if current != wanted:
            findings.append(
                f"{tid} ({entry['doc']}): DRIFT — the doc's region between the "
                f"typed-table:BEGIN/END anchors no longer matches "
                f"{entry['builder'].__module__}.{entry['builder'].__name__}()'s current "
                f"output. Run 'python3 tools/doc_table_generation.py --write "
                f"--table {tid}' to regenerate, or fix the builder if the DOC is right and "
                f"the call site is stale (ADR-0012 P1: the call site is the one home — never "
                f"hand-edit the doc region directly)."
            )
    return findings


def write(table_ids: "list | None" = None) -> list:
    """Regenerate the doc region for each named (or every registered) table in place. Returns
    the list of doc-relative paths actually touched (a doc already byte-identical to its
    builder's output is left untouched — no spurious mtime/diff churn)."""
    ids = table_ids or sorted(REGISTRY)
    touched = []
    for tid in ids:
        entry = REGISTRY[tid]
        doc_path = REPO_ROOT / entry["doc"]
        lines, b, e, current = _region(doc_path, tid)
        wanted = render(tid)
        if current == wanted:
            continue
        new_lines = lines[:b + 1] + wanted.split("\n") + lines[e:]
        doc_path.write_text("\n".join(new_lines), encoding="utf-8")
        touched.append(entry["doc"])
    return touched


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true",
                     help="regenerate registered doc region(s) in place (default: check only)")
    ap.add_argument("--table", nargs="*", dest="table_ids", metavar="ID",
                     help="restrict to these registered table id(s) (default: all)")
    args = ap.parse_args(argv)
    bad = [t for t in (args.table_ids or []) if t not in REGISTRY]
    if bad:
        print(f"doc_table_generation: unknown table id(s) {bad} — known: {sorted(REGISTRY)}",
              file=sys.stderr)
        return 2
    if args.write:
        touched = write(args.table_ids)
        if touched:
            print(f"doc_table_generation: regenerated {len(touched)} doc region(s): {touched}")
        else:
            print("doc_table_generation: nothing to regenerate — already current")
        return 0
    findings = check(args.table_ids)
    if findings:
        print(f"doc_table_generation: {len(findings)} drift finding(s):\n")
        for f in findings:
            print(f"  !! {f}")
        return 1
    print(f"doc_table_generation: clean — {len(args.table_ids or REGISTRY)} registered table(s) "
          f"match their builder's current output ✓")
    return 0


if __name__ == "__main__":
    sys.exit(main())
